apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: basant827009/fibonacii-login-calculator:latest
      env:
      - name: REDIS_HOST
        value: redis
      - name: REDIS_PORT
        value: 6379

 

        
